-- The home base of every spawn site in one tile of the Afghanistan map: its nearest base with a domain, by
-- straight line, and how far. The same sites, in the same order, as ..\spawn_sites\tile_x+0200_z+0500.lua (survey run 2026-10-08_1301);
-- see ..\base_domains.lua for the bases. Generated by map_data_tools/find_base_domains.py; do not hand-edit.
-- One site per line: number, home base id (DCS's airbase id), distance from its centre in metres.

SITE_DOMAINS_TILE = {
    tile = "tile_x+0200_z+0500",
    sites = {
        { 199440, 19, 195655 },
        { 200193, 19, 196660 },
        { 205455, 19, 226505 },
        { 217147, 19, 260970 },
        { 217667, 19, 262953 },
        { 222406, 19, 258022 },
        { 222860, 19, 259591 },
        { 223184, 19, 259951 },
        { 223225, 19, 260832 },
        { 223341, 19, 261620 },
        { 223434, 19, 260039 },
        { 223550, 19, 261138 },
        { 223708, 19, 262114 },
        { 223800, 19, 261226 },
        { 224039, 19, 263752 },
        { 224233, 19, 262846 },
        { 224322, 19, 263916 },
        { 224432, 19, 265562 },
        { 224464, 19, 264948 },
        { 224664, 19, 264202 },
        { 224744, 19, 264954 },
        { 224781, 19, 265999 },
        { 225075, 19, 265951 },
    },
}
