-- The home base of every spawn site in one tile of the Afghanistan map: its nearest base with a domain, by
-- straight line, and how far. The same sites, in the same order, as ..\spawn_sites\tile_x+0000_z+0000.lua (survey run 2026-10-08_1301);
-- see ..\base_domains.lua for the bases. Generated by map_data_tools/find_base_domains.py; do not hand-edit.
-- One site per line: number, home base id (DCS's airbase id), distance from its centre in metres.

SITE_DOMAINS_TILE = {
    tile = "tile_x+0000_z+0000",
    sites = {
        { 180806, 18, 116473 },
        { 180873, 5, 108617 },
        { 181601, 5, 118629 },
        { 181713, 5, 119604 },
        { 182559, 18, 118410 },
        { 182855, 5, 105281 },
        { 182856, 5, 106881 },
        { 183000, 5, 108385 },
        { 183616, 18, 87519 },
        { 183732, 5, 116387 },
        { 185896, 18, 86049 },
        { 186081, 18, 88227 },
        { 186116, 18, 89948 },
        { 186117, 18, 86425 },
        { 186336, 18, 87084 },
        { 186356, 18, 85593 },
        { 186496, 18, 85781 },
        { 186865, 18, 90399 },
        { 186885, 18, 92649 },
        { 187040, 18, 92519 },
        { 187084, 18, 70796 },
        { 187129, 18, 93538 },
        { 187208, 18, 59898 },
        { 187266, 18, 93326 },
        { 187387, 18, 96220 },
        { 187388, 18, 95225 },
        { 187513, 18, 96529 },
        { 187694, 18, 56663 },
        { 187838, 18, 41702 },
        { 187938, 18, 51461 },
    },
}
