-- The home base of every spawn site in one tile of the Afghanistan map: its nearest base with a domain, by
-- straight line, and how far. The same sites, in the same order, as ..\spawn_sites\tile_x+0200_z+0400.lua (survey run 2026-10-08_1301);
-- see ..\base_domains.lua for the bases. Generated by map_data_tools/find_base_domains.py; do not hand-edit.
-- One site per line: number, home base id (DCS's airbase id), distance from its centre in metres.

SITE_DOMAINS_TILE = {
    tile = "tile_x+0200_z+0400",
    sites = {
        { 209573, 16, 182000 },
        { 214892, 19, 212037 },
        { 218503, 19, 212564 },
        { 218854, 19, 213523 },
        { 220173, 19, 237529 },
        { 225384, 19, 249263 },
        { 225481, 19, 249951 },
    },
}
