-- The home base of every spawn site in one tile of the Afghanistan map: its nearest base with a domain, by
-- straight line, and how far. The same sites, in the same order, as ..\spawn_sites\tile_x+0300_z+0400.lua (survey run 2026-10-08_1301);
-- see ..\base_domains.lua for the bases. Generated by map_data_tools/find_base_domains.py; do not hand-edit.
-- One site per line: number, home base id (DCS's airbase id), distance from its centre in metres.

SITE_DOMAINS_TILE = {
    tile = "tile_x+0300_z+0400",
    sites = {
        { 231965, 19, 246954 },
        { 234368, 19, 251067 },
        { 235093, 19, 252309 },
        { 235154, 19, 252660 },
        { 235707, 19, 254032 },
        { 239761, 19, 261597 },
        { 240351, 19, 262760 },
        { 242090, 19, 265938 },
        { 244297, 19, 276118 },
        { 244347, 19, 275896 },
        { 244408, 19, 277343 },
        { 244898, 19, 275822 },
        { 244899, 19, 279029 },
        { 244949, 19, 280390 },
        { 245258, 19, 280101 },
        { 245596, 19, 276694 },
        { 245660, 19, 282641 },
        { 246132, 19, 276069 },
        { 246378, 19, 284335 },
        { 246436, 19, 276046 },
        { 247874, 19, 278615 },
        { 248050, 19, 287799 },
        { 248396, 19, 288868 },
        { 248572, 19, 279577 },
        { 249232, 19, 290575 },
        { 249233, 19, 290945 },
        { 249323, 19, 280732 },
    },
}
