"""Extract the Kola map's airfield radio frequencies into kola_f16/data/airfield_frequencies.lua.

    python kola_data_tools/airfield_frequencies.py [--dcs "C:\\Program Files\\Eagle Dynamics\\DCS World"] [--out ...]

Source: <DCS>\\Mods\\terrains\\Kola\\radio.lua, the map's own airfield radios (the tower /
ground / approach frequencies DCS's ATC uses, as on the airfield charts). Each entry's
radioId is "airfield<N>_0", N being the airbase's DCS id (Airbase:getID()), so the mission
looks a base up by its id. Per airfield: its ICAO-style label from the file's comment,
the VHF (118-136 MHz, the AN/ARC-222's band) and UHF tower frequencies in MHz.

The airfield traffic calls (roadmap.md item 7) go out on each field's VHF frequency.
Regex-driven: the file calls dofile and _(), which the table reader in dcslua.py doesn't
evaluate. Stdlib only.
"""

import argparse
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
MISSION_DIR = os.path.dirname(HERE)

DEFAULT_DCS = r"C:\Program Files\Eagle Dynamics\DCS World"
DEFAULT_OUT = os.path.join(MISSION_DIR, "kola_f16", "data", "airfield_frequencies.lua")

LABEL = re.compile(r"^\s*--\s*(\S.*?)\s*$")
RADIO_ID = re.compile(r"radioId\s*=\s*'airfield(\d+)_0'")
BAND = re.compile(r"\[(VHF_HI|UHF)\]\s*=\s*\{\s*MODULATIONTYPE_\w+\s*,\s*([\d.]+)\s*\}")


def read(path):
    out, label = [], None
    entry = None
    for line in open(path, encoding="utf-8", errors="replace"):
        m = LABEL.match(line)
        if m:
            label = m.group(1)
            continue
        m = RADIO_ID.search(line)
        if m:
            entry = {"id": int(m.group(1)), "label": label or "?"}
            out.append(entry)
            continue
        if entry is not None and "frequency" in line:
            for band, hz in BAND.findall(line):
                entry["vhf" if band == "VHF_HI" else "uhf"] = float(hz) / 1e6
    return [e for e in out if "vhf" in e]


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dcs", default=DEFAULT_DCS)
    parser.add_argument("--out", default=DEFAULT_OUT)
    args = parser.parse_args()
    source = os.path.join(args.dcs, "Mods", "terrains", "Kola", "radio.lua")
    entries = sorted(read(source), key=lambda e: e["id"])
    lines = [
        "-- The Kola map's airfield radio frequencies, by DCS airbase id (Airbase:getID()).",
        "-- GENERATED by kola_data_tools/airfield_frequencies.py from",
        "-- Mods\\terrains\\Kola\\radio.lua; don't edit by hand. MHz; vhf is the AN/ARC-222's band.",
        "",
        "AIRFIELD_FREQUENCIES = {",
    ]
    for e in entries:
        lines.append("    [%d] = { label = %-30s vhf = %.3f, uhf = %.3f }," % (
            e["id"], '"%s",' % e["label"].replace('"', ""), e["vhf"], e.get("uhf", 0)))
    lines.append("}")
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d airfields to %s" % (len(entries), args.out))


if __name__ == "__main__":
    main()
