-- One loadout per aircraft type and mission type, for AI flights. Generated by
-- tools/aircraft_loadouts.py from ED's UnitPayloads, DCS Liberation's AI loadouts and
-- our own proven hand loadouts; which one is chosen lives in
-- tools/aircraft_loadout_choices.json. Do not hand-edit: change the choice and re-run.
-- Plain data, no logic. Every CLSID was checked against data/aircraft_pylons.lua.
--   AIRCRAFT_LOADOUT[type][mission type] = { source, name, fuel, chaff, flare, gun,
--       pylons = { { num, CLSID } } }   (trailing comment = weapon name)

AIRCRAFT_LOADOUT = {
    ["A-10C_2"] = {
        close_air_support = {
            source = "hand", name = "Syria CAS",
            fuel = 5029, chaff = 240, flare = 240, gun = 100,
            pylons = {
                { num = 1, CLSID = "{DB434044-F5D0-4F1F-9BA9-B73027E18DD3}" },  -- LAU-105 - 2 x AIM-9M Sidewinder IR AAM
                { num = 2, CLSID = "{A111396E-D3E8-4b9c-8AC9-2432489304D5}" },  -- AN/AAQ-28 LITENING - Targeting Pod
                { num = 3, CLSID = "{DAC53A2F-79CA-42FF-A77A-F5649B601308}" },  -- LAU-88 - 3 x AGM-65D - Maverick D (IIR ASM)
                { num = 9, CLSID = "{DAC53A2F-79CA-42FF-A77A-F5649B601308}" },  -- LAU-88 - 3 x AGM-65D - Maverick D (IIR ASM)
                { num = 10, CLSID = "{CBU-87}" },  -- CBU-87 - 202 x CEM Cluster Bomb
                { num = 11, CLSID = "{DB434044-F5D0-4F1F-9BA9-B73027E18DD3}" },  -- LAU-105 - 2 x AIM-9M Sidewinder IR AAM
            },
        },
    },
    ["B-1B"] = {
        strike = {
            source = "liberation", name = "Liberation Strike",
            fuel = 88450, chaff = 480, flare = 48, gun = 100,
            pylons = {
                { num = 1, CLSID = "GBU-31V3B*8" },  -- MPRL - 8 x GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 2, CLSID = "GBU-31V3B*8" },  -- MPRL - 8 x GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 3, CLSID = "GBU-31V3B*8" },  -- MPRL - 8 x GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
            },
        },
        airfield_strike = {
            source = "liberation", name = "Liberation OCA/Aircraft",
            fuel = 88450, chaff = 480, flare = 48, gun = 100,
            pylons = {
                { num = 1, CLSID = "GBU-31V3B*8" },  -- MPRL - 8 x GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 2, CLSID = "GBU-31V3B*8" },  -- MPRL - 8 x GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 3, CLSID = "GBU-31V3B*8" },  -- MPRL - 8 x GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
            },
        },
        interdiction = {
            source = "liberation", name = "Liberation BAI",
            fuel = 88450, chaff = 480, flare = 48, gun = 100,
            pylons = {
                { num = 1, CLSID = "GBU-31*8" },  -- MPRL - 8 x GBU-31(V)1/B - JDAM, 2000lb GPS Guided Bomb
                { num = 2, CLSID = "GBU-31*8" },  -- MPRL - 8 x GBU-31(V)1/B - JDAM, 2000lb GPS Guided Bomb
                { num = 3, CLSID = "GBU-31*8" },  -- MPRL - 8 x GBU-31(V)1/B - JDAM, 2000lb GPS Guided Bomb
            },
        },
    },
    ["F-15ESE"] = {
        strike = {
            source = "liberation", name = "Liberation Strike",
            fuel = 10245.53, chaff = 120, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 2, CLSID = "{GBU-31V3B}" },  -- GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 3, CLSID = "{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}" },  -- AIM-9M Sidewinder IR AAM
                { num = 4, CLSID = "{CFT_L_GBU_31V3B_x_2}" },  -- GBU-31(V)3/B * 2
                { num = 7, CLSID = "{F-15E_AAQ-14_LANTIRN}" },  -- AN/AAQ-14 LANTIRN TGT Pod
                { num = 8, CLSID = "{F15E_EXTTANK}" },  -- Fuel tank 610 gal
                { num = 9, CLSID = "{F-15E_AAQ-13_LANTIRN}" },  -- AN/AAQ-13 LANTIRN NAV POD
                { num = 12, CLSID = "{CFT_R_GBU_31V3B_x_2}" },  -- GBU-31(V)3/B * 2
                { num = 13, CLSID = "{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}" },  -- AIM-9M Sidewinder IR AAM
                { num = 14, CLSID = "{GBU-31V3B}" },  -- GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 15, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
            },
        },
        airfield_strike = {
            source = "liberation", name = "Liberation OCA/Aircraft",
            fuel = 10245.53, chaff = 120, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 2, CLSID = "{GBU-31V3B}" },  -- GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 3, CLSID = "{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}" },  -- AIM-9M Sidewinder IR AAM
                { num = 4, CLSID = "{CFT_L_GBU_31V3B_x_2}" },  -- GBU-31(V)3/B * 2
                { num = 7, CLSID = "{F-15E_AAQ-14_LANTIRN}" },  -- AN/AAQ-14 LANTIRN TGT Pod
                { num = 8, CLSID = "{F15E_EXTTANK}" },  -- Fuel tank 610 gal
                { num = 9, CLSID = "{F-15E_AAQ-13_LANTIRN}" },  -- AN/AAQ-13 LANTIRN NAV POD
                { num = 12, CLSID = "{CFT_R_GBU_31V3B_x_2}" },  -- GBU-31(V)3/B * 2
                { num = 13, CLSID = "{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}" },  -- AIM-9M Sidewinder IR AAM
                { num = 14, CLSID = "{GBU-31V3B}" },  -- GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 15, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
            },
        },
        destruction_of_air_defenses = {
            source = "liberation", name = "Liberation DEAD",
            fuel = 10245.53, chaff = 120, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 2, CLSID = "{GBU-31V3B}" },  -- GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 3, CLSID = "{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}" },  -- AIM-9M Sidewinder IR AAM
                { num = 4, CLSID = "{CFT_L_GBU_31V3B_x_2}" },  -- GBU-31(V)3/B * 2
                { num = 7, CLSID = "{F-15E_AAQ-14_LANTIRN}" },  -- AN/AAQ-14 LANTIRN TGT Pod
                { num = 8, CLSID = "{F15E_EXTTANK}" },  -- Fuel tank 610 gal
                { num = 9, CLSID = "{F-15E_AAQ-13_LANTIRN}" },  -- AN/AAQ-13 LANTIRN NAV POD
                { num = 12, CLSID = "{CFT_R_GBU_31V3B_x_2}" },  -- GBU-31(V)3/B * 2
                { num = 13, CLSID = "{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}" },  -- AIM-9M Sidewinder IR AAM
                { num = 14, CLSID = "{GBU-31V3B}" },  -- GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 15, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
            },
        },
        interdiction = {
            source = "liberation", name = "Liberation BAI",
            fuel = 10245.53, chaff = 120, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 2, CLSID = "{GBU-31V3B}" },  -- GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 3, CLSID = "{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}" },  -- AIM-9M Sidewinder IR AAM
                { num = 4, CLSID = "{CFT_L_GBU_31V3B_x_2}" },  -- GBU-31(V)3/B * 2
                { num = 7, CLSID = "{F-15E_AAQ-14_LANTIRN}" },  -- AN/AAQ-14 LANTIRN TGT Pod
                { num = 8, CLSID = "{F15E_EXTTANK}" },  -- Fuel tank 610 gal
                { num = 9, CLSID = "{F-15E_AAQ-13_LANTIRN}" },  -- AN/AAQ-13 LANTIRN NAV POD
                { num = 12, CLSID = "{CFT_R_GBU_31V3B_x_2}" },  -- GBU-31(V)3/B * 2
                { num = 13, CLSID = "{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}" },  -- AIM-9M Sidewinder IR AAM
                { num = 14, CLSID = "{GBU-31V3B}" },  -- GBU-31(V)3/B - JDAM, 2000lb GPS Guided Penetrator Bomb
                { num = 15, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
            },
        },
    },
    ["F-16C_50"] = {
        strike = {
            source = "liberation", name = "Liberation Strike",
            fuel = 3249, chaff = 60, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 2, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 3, CLSID = "{GBU-31}" },  -- GBU-31(V)1/B - JDAM, 2000lb GPS Guided Bomb
                { num = 4, CLSID = "{F376DBEE-4CAE-41BA-ADD9-B2910AC95DEC}" },  -- Fuel tank 370 gal
                { num = 5, CLSID = "ALQ_184" },  -- ALQ-184 - ECM Pod
                { num = 6, CLSID = "{F376DBEE-4CAE-41BA-ADD9-B2910AC95DEC}" },  -- Fuel tank 370 gal
                { num = 7, CLSID = "{GBU-31}" },  -- GBU-31(V)1/B - JDAM, 2000lb GPS Guided Bomb
                { num = 8, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 9, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 11, CLSID = "{A111396E-D3E8-4b9c-8AC9-2432489304D5}" },  -- AN/AAQ-28 LITENING - Targeting Pod
            },
        },
        airfield_strike = {
            source = "liberation", name = "Liberation Strike",
            fuel = 3249, chaff = 60, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 2, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 3, CLSID = "{GBU-31}" },  -- GBU-31(V)1/B - JDAM, 2000lb GPS Guided Bomb
                { num = 4, CLSID = "{F376DBEE-4CAE-41BA-ADD9-B2910AC95DEC}" },  -- Fuel tank 370 gal
                { num = 5, CLSID = "ALQ_184" },  -- ALQ-184 - ECM Pod
                { num = 6, CLSID = "{F376DBEE-4CAE-41BA-ADD9-B2910AC95DEC}" },  -- Fuel tank 370 gal
                { num = 7, CLSID = "{GBU-31}" },  -- GBU-31(V)1/B - JDAM, 2000lb GPS Guided Bomb
                { num = 8, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 9, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 11, CLSID = "{A111396E-D3E8-4b9c-8AC9-2432489304D5}" },  -- AN/AAQ-28 LITENING - Targeting Pod
            },
        },
        suppression_of_air_defenses = {
            source = "liberation", name = "Liberation SEAD",
            fuel = 3249, chaff = 60, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 2, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 3, CLSID = "{B06DD79A-F21E-4EB9-BD9D-AB3844618C93}" },  -- AGM-88C HARM - High Speed Anti-Radiation Missile
                { num = 4, CLSID = "{F376DBEE-4CAE-41BA-ADD9-B2910AC95DEC}" },  -- Fuel tank 370 gal
                { num = 5, CLSID = "ALQ_184" },  -- ALQ-184 - ECM Pod
                { num = 6, CLSID = "{F376DBEE-4CAE-41BA-ADD9-B2910AC95DEC}" },  -- Fuel tank 370 gal
                { num = 7, CLSID = "{B06DD79A-F21E-4EB9-BD9D-AB3844618C93}" },  -- AGM-88C HARM - High Speed Anti-Radiation Missile
                { num = 8, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 9, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 10, CLSID = "{AN_ASQ_213}" },  -- AN/ASQ-213 HTS - HARM Targeting System
                { num = 11, CLSID = "{A111396E-D3E8-4b9c-8AC9-2432489304D5}" },  -- AN/AAQ-28 LITENING - Targeting Pod
            },
        },
        destruction_of_air_defenses = {
            source = "liberation", name = "Liberation DEAD",
            fuel = 3249, chaff = 60, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 2, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 3, CLSID = "{AGM-154A}" },  -- AGM-154A - JSOW CEB (CBU-type)
                { num = 4, CLSID = "{F376DBEE-4CAE-41BA-ADD9-B2910AC95DEC}" },  -- Fuel tank 370 gal
                { num = 5, CLSID = "ALQ_184" },  -- ALQ-184 - ECM Pod
                { num = 6, CLSID = "{F376DBEE-4CAE-41BA-ADD9-B2910AC95DEC}" },  -- Fuel tank 370 gal
                { num = 7, CLSID = "{AGM-154A}" },  -- AGM-154A - JSOW CEB (CBU-type)
                { num = 8, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 9, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 10, CLSID = "{AN_ASQ_213}" },  -- AN/ASQ-213 HTS - HARM Targeting System
                { num = 11, CLSID = "{A111396E-D3E8-4b9c-8AC9-2432489304D5}" },  -- AN/AAQ-28 LITENING - Targeting Pod
            },
        },
        close_air_support = {
            source = "hand", name = "Syria CAS",
            fuel = 3249, chaff = 60, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}" },  -- AIM-9M Sidewinder IR AAM
                { num = 2, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 3, CLSID = "{DAC53A2F-79CA-42FF-A77A-F5649B601308}" },  -- LAU-88 - 3 x AGM-65D - Maverick D (IIR ASM)
                { num = 7, CLSID = "{DAC53A2F-79CA-42FF-A77A-F5649B601308}" },  -- LAU-88 - 3 x AGM-65D - Maverick D (IIR ASM)
                { num = 8, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 9, CLSID = "{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}" },  -- AIM-9M Sidewinder IR AAM
                { num = 11, CLSID = "{A111396E-D3E8-4b9c-8AC9-2432489304D5}" },  -- AN/AAQ-28 LITENING - Targeting Pod
            },
        },
    },
    ["FA-18C_hornet"] = {
        strike = {
            source = "liberation", name = "STRIKE",
            fuel = 4900, chaff = 60, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 2, CLSID = "{GBU_31_V_2B}" },  -- GBU-31(V)2/B - JDAM, 2000lb GPS Guided Bomb
                { num = 3, CLSID = "{FPU_8A_FUEL_TANK}" },  -- FPU-8A Fuel Tank 330 gallons
                { num = 4, CLSID = "{AN_ASQ_228}" },  -- AN/ASQ-228 ATFLIR - Targeting Pod
                { num = 6, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 7, CLSID = "{FPU_8A_FUEL_TANK}" },  -- FPU-8A Fuel Tank 330 gallons
                { num = 8, CLSID = "{GBU_31_V_2B}" },  -- GBU-31(V)2/B - JDAM, 2000lb GPS Guided Bomb
                { num = 9, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
            },
        },
        airfield_strike = {
            source = "liberation", name = "STRIKE",
            fuel = 4900, chaff = 60, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 2, CLSID = "{GBU_31_V_2B}" },  -- GBU-31(V)2/B - JDAM, 2000lb GPS Guided Bomb
                { num = 3, CLSID = "{FPU_8A_FUEL_TANK}" },  -- FPU-8A Fuel Tank 330 gallons
                { num = 4, CLSID = "{AN_ASQ_228}" },  -- AN/ASQ-228 ATFLIR - Targeting Pod
                { num = 6, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 7, CLSID = "{FPU_8A_FUEL_TANK}" },  -- FPU-8A Fuel Tank 330 gallons
                { num = 8, CLSID = "{GBU_31_V_2B}" },  -- GBU-31(V)2/B - JDAM, 2000lb GPS Guided Bomb
                { num = 9, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
            },
        },
        suppression_of_air_defenses = {
            source = "liberation", name = "Liberation SEAD",
            fuel = 4900, chaff = 60, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 2, CLSID = "{B06DD79A-F21E-4EB9-BD9D-AB3844618C93}" },  -- AGM-88C HARM - High Speed Anti-Radiation Missile
                { num = 3, CLSID = "{FPU_8A_FUEL_TANK}" },  -- FPU-8A Fuel Tank 330 gallons
                { num = 4, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 6, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 7, CLSID = "{FPU_8A_FUEL_TANK}" },  -- FPU-8A Fuel Tank 330 gallons
                { num = 8, CLSID = "{B06DD79A-F21E-4EB9-BD9D-AB3844618C93}" },  -- AGM-88C HARM - High Speed Anti-Radiation Missile
                { num = 9, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
            },
        },
        destruction_of_air_defenses = {
            source = "liberation", name = "Liberation DEAD",
            fuel = 4900, chaff = 60, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 2, CLSID = "{BRU55_2*AGM-154A}" },  -- BRU-55 with 2 x AGM-154A - JSOW CEB (CBU-type)
                { num = 3, CLSID = "{FPU_8A_FUEL_TANK}" },  -- FPU-8A Fuel Tank 330 gallons
                { num = 4, CLSID = "{AN_ASQ_228}" },  -- AN/ASQ-228 ATFLIR - Targeting Pod
                { num = 6, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 7, CLSID = "{FPU_8A_FUEL_TANK}" },  -- FPU-8A Fuel Tank 330 gallons
                { num = 8, CLSID = "{BRU55_2*AGM-154A}" },  -- BRU-55 with 2 x AGM-154A - JSOW CEB (CBU-type)
                { num = 9, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
            },
        },
        close_air_support = {
            source = "hand", name = "Syria CAS",
            fuel = 4900, chaff = 60, flare = 60, gun = 100,
            pylons = {
                { num = 1, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
                { num = 2, CLSID = "LAU_117_AGM_65F" },  -- LAU-117 - AGM-65F - Maverick F (IIR ASM)
                { num = 3, CLSID = "{GBU-38}" },  -- GBU-38(V)1/B - JDAM, 500lb GPS Guided Bomb
                { num = 4, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 5, CLSID = "{A111396E-D3E8-4b9c-8AC9-2432489304D5}" },  -- AN/AAQ-28 LITENING - Targeting Pod
                { num = 6, CLSID = "{40EF17B7-F508-45de-8566-6FFECC0C1AB8}" },  -- AIM-120C AMRAAM - Active Radar AAM
                { num = 7, CLSID = "{GBU-38}" },  -- GBU-38(V)1/B - JDAM, 500lb GPS Guided Bomb
                { num = 8, CLSID = "LAU_117_AGM_65F" },  -- LAU-117 - AGM-65F - Maverick F (IIR ASM)
                { num = 9, CLSID = "{5CE2FF2A-645A-4197-B48D-8720AC69394F}" },  -- AIM-9X Sidewinder IR AAM
            },
        },
    },
    ["Su-24M"] = {
        strike = {
            source = "dcs", name = "FAB-500*4,R-60M*2",
            fuel = 11700, chaff = 96, flare = 96, gun = 100,
            pylons = {
                { num = 1, CLSID = "{APU-60-1_R_60M}" },  -- APU-60-1M with R-60M (AA-8 Aphid-B) - IR AAM
                { num = 2, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 3, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 6, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 7, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 8, CLSID = "{APU-60-1_R_60M}" },  -- APU-60-1M with R-60M (AA-8 Aphid-B) - IR AAM
            },
        },
        airfield_strike = {
            source = "dcs", name = "RBK-250*8",
            fuel = 11700, chaff = 96, flare = 96, gun = 100,
            pylons = {
                { num = 1, CLSID = "{4203753F-8198-4E85-9924-6F8FF679F9FF}" },  -- RBK-250 - 42 x PTAB-2.5M, 250kg CBU Medium HEAT/AP
                { num = 2, CLSID = "{4203753F-8198-4E85-9924-6F8FF679F9FF}" },  -- RBK-250 - 42 x PTAB-2.5M, 250kg CBU Medium HEAT/AP
                { num = 3, CLSID = "{4203753F-8198-4E85-9924-6F8FF679F9FF}" },  -- RBK-250 - 42 x PTAB-2.5M, 250kg CBU Medium HEAT/AP
                { num = 4, CLSID = "{4203753F-8198-4E85-9924-6F8FF679F9FF}" },  -- RBK-250 - 42 x PTAB-2.5M, 250kg CBU Medium HEAT/AP
                { num = 5, CLSID = "{4203753F-8198-4E85-9924-6F8FF679F9FF}" },  -- RBK-250 - 42 x PTAB-2.5M, 250kg CBU Medium HEAT/AP
                { num = 6, CLSID = "{4203753F-8198-4E85-9924-6F8FF679F9FF}" },  -- RBK-250 - 42 x PTAB-2.5M, 250kg CBU Medium HEAT/AP
                { num = 7, CLSID = "{4203753F-8198-4E85-9924-6F8FF679F9FF}" },  -- RBK-250 - 42 x PTAB-2.5M, 250kg CBU Medium HEAT/AP
                { num = 8, CLSID = "{4203753F-8198-4E85-9924-6F8FF679F9FF}" },  -- RBK-250 - 42 x PTAB-2.5M, 250kg CBU Medium HEAT/AP
            },
        },
        suppression_of_air_defenses = {
            source = "liberation", name = "SEAD",
            fuel = 11700, chaff = 96, flare = 96, gun = 100,
            pylons = {
                { num = 1, CLSID = "{E86C5AA5-6D49-4F00-AD2E-79A62D6DDE26}" },  -- Kh-25MPU (Updated AS-12 Kegler) - 320kg, ARM, IN & Pas Rdr
                { num = 2, CLSID = "{FE382A68-8620-4AC0-BDF5-709BFE3977D7}" },  -- Kh-58U (AS-11 Kilter) - 640kg, ARM, IN & Pas Rdr
                { num = 7, CLSID = "{FE382A68-8620-4AC0-BDF5-709BFE3977D7}" },  -- Kh-58U (AS-11 Kilter) - 640kg, ARM, IN & Pas Rdr
                { num = 8, CLSID = "{E86C5AA5-6D49-4F00-AD2E-79A62D6DDE26}" },  -- Kh-25MPU (Updated AS-12 Kegler) - 320kg, ARM, IN & Pas Rdr
            },
        },
    },
    ["Su-34"] = {
        strike = {
            source = "dcs", name = "FAB-500*8,R-73*2,ECM",
            fuel = 9800, chaff = 64, flare = 64, gun = 100,
            pylons = {
                { num = 1, CLSID = "{44EE8698-89F9-48EE-AF36-5FD31896A82F}" },  -- L005 Sorbtsiya ECM pod (left)
                { num = 2, CLSID = "{FBC29BFE-3D24-4C64-B81D-941239D12249}" },  -- R-73 (AA-11 Archer) - Infra Red
                { num = 3, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 4, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 5, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 6, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 7, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 8, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 9, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 10, CLSID = "{37DCC01E-9E02-432F-B61D-10C166CA2798}" },  -- FAB-500M-62 - 500 kg GP Bomb LD
                { num = 11, CLSID = "{FBC29BFE-3D24-4C64-B81D-941239D12249}" },  -- R-73 (AA-11 Archer) - Infra Red
                { num = 12, CLSID = "{44EE8698-89F9-48EE-AF36-5FD31896A82A}" },  -- L005 Sorbtsiya ECM pod (right)
            },
        },
        airfield_strike = {
            source = "liberation", name = "Liberation Strike",
            fuel = 9800, chaff = 64, flare = 64, gun = 100,
            pylons = {
                { num = 1, CLSID = "{ECM_POD_L_175V}" },  -- L175V Khibiny ECM pod
                { num = 2, CLSID = "{FBC29BFE-3D24-4C64-B81D-941239D12249}" },  -- R-73 (AA-11 Archer) - Infra Red
                { num = 3, CLSID = "{D5435F26-F120-4FA3-9867-34ACE562EF1B}" },  -- RBK-500-255 - 30 x PTAB-10-5, 500kg CBU Heavy HEAT/AP
                { num = 4, CLSID = "{D5435F26-F120-4FA3-9867-34ACE562EF1B}" },  -- RBK-500-255 - 30 x PTAB-10-5, 500kg CBU Heavy HEAT/AP
                { num = 5, CLSID = "{D5435F26-F120-4FA3-9867-34ACE562EF1B}" },  -- RBK-500-255 - 30 x PTAB-10-5, 500kg CBU Heavy HEAT/AP
                { num = 6, CLSID = "{D5435F26-F120-4FA3-9867-34ACE562EF1B}" },  -- RBK-500-255 - 30 x PTAB-10-5, 500kg CBU Heavy HEAT/AP
                { num = 7, CLSID = "{D5435F26-F120-4FA3-9867-34ACE562EF1B}" },  -- RBK-500-255 - 30 x PTAB-10-5, 500kg CBU Heavy HEAT/AP
                { num = 8, CLSID = "{D5435F26-F120-4FA3-9867-34ACE562EF1B}" },  -- RBK-500-255 - 30 x PTAB-10-5, 500kg CBU Heavy HEAT/AP
                { num = 9, CLSID = "{D5435F26-F120-4FA3-9867-34ACE562EF1B}" },  -- RBK-500-255 - 30 x PTAB-10-5, 500kg CBU Heavy HEAT/AP
                { num = 10, CLSID = "{D5435F26-F120-4FA3-9867-34ACE562EF1B}" },  -- RBK-500-255 - 30 x PTAB-10-5, 500kg CBU Heavy HEAT/AP
                { num = 11, CLSID = "{FBC29BFE-3D24-4C64-B81D-941239D12249}" },  -- R-73 (AA-11 Archer) - Infra Red
                { num = 12, CLSID = "{ECM_POD_L_175V}" },  -- L175V Khibiny ECM pod
            },
        },
        suppression_of_air_defenses = {
            source = "liberation", name = "Liberation SEAD",
            fuel = 9800, chaff = 64, flare = 64, gun = 100,
            pylons = {
                { num = 1, CLSID = "{ECM_POD_L_175V}" },  -- L175V Khibiny ECM pod
                { num = 2, CLSID = "{FBC29BFE-3D24-4C64-B81D-941239D12249}" },  -- R-73 (AA-11 Archer) - Infra Red
                { num = 3, CLSID = "{X-31P}" },  -- Kh-31P (AS-17 Krypton) - 600kg, ARM, IN & Pas Rdr
                { num = 4, CLSID = "{X-31P}" },  -- Kh-31P (AS-17 Krypton) - 600kg, ARM, IN & Pas Rdr
                { num = 6, CLSID = "{9B25D316-0434-4954-868F-D51DB1A38DF0}" },  -- R-27R (AA-10 Alamo A) - Semi-Act Rdr
                { num = 7, CLSID = "{9B25D316-0434-4954-868F-D51DB1A38DF0}" },  -- R-27R (AA-10 Alamo A) - Semi-Act Rdr
                { num = 9, CLSID = "{X-31P}" },  -- Kh-31P (AS-17 Krypton) - 600kg, ARM, IN & Pas Rdr
                { num = 10, CLSID = "{X-31P}" },  -- Kh-31P (AS-17 Krypton) - 600kg, ARM, IN & Pas Rdr
                { num = 11, CLSID = "{FBC29BFE-3D24-4C64-B81D-941239D12249}" },  -- R-73 (AA-11 Archer) - Infra Red
                { num = 12, CLSID = "{ECM_POD_L_175V}" },  -- L175V Khibiny ECM pod
            },
        },
        destruction_of_air_defenses = {
            source = "dcs", name = "Kh-29T*4,R-73*2,R-27R*2,ECM",
            fuel = 9800, chaff = 64, flare = 64, gun = 100,
            pylons = {
                { num = 1, CLSID = "{44EE8698-89F9-48EE-AF36-5FD31896A82F}" },  -- L005 Sorbtsiya ECM pod (left)
                { num = 2, CLSID = "{FBC29BFE-3D24-4C64-B81D-941239D12249}" },  -- R-73 (AA-11 Archer) - Infra Red
                { num = 3, CLSID = "{X-29T}" },  -- Kh-29T (AS-14 Kedge) - 670kg, ASM, TV Guided
                { num = 4, CLSID = "{X-29T}" },  -- Kh-29T (AS-14 Kedge) - 670kg, ASM, TV Guided
                { num = 6, CLSID = "{9B25D316-0434-4954-868F-D51DB1A38DF0}" },  -- R-27R (AA-10 Alamo A) - Semi-Act Rdr
                { num = 7, CLSID = "{9B25D316-0434-4954-868F-D51DB1A38DF0}" },  -- R-27R (AA-10 Alamo A) - Semi-Act Rdr
                { num = 9, CLSID = "{X-29T}" },  -- Kh-29T (AS-14 Kedge) - 670kg, ASM, TV Guided
                { num = 10, CLSID = "{X-29T}" },  -- Kh-29T (AS-14 Kedge) - 670kg, ASM, TV Guided
                { num = 11, CLSID = "{FBC29BFE-3D24-4C64-B81D-941239D12249}" },  -- R-73 (AA-11 Archer) - Infra Red
                { num = 12, CLSID = "{44EE8698-89F9-48EE-AF36-5FD31896A82A}" },  -- L005 Sorbtsiya ECM pod (right)
            },
        },
        interdiction = {
            source = "liberation", name = "Liberation CAS",
            fuel = 9800, chaff = 64, flare = 64, gun = 100,
            pylons = {
                { num = 1, CLSID = "{ECM_POD_L_175V}" },  -- L175V Khibiny ECM pod
                { num = 2, CLSID = "{FBC29BFE-3D24-4C64-B81D-941239D12249}" },  -- R-73 (AA-11 Archer) - Infra Red
                { num = 3, CLSID = "{X-29L}" },  -- Kh-29L (AS-14 Kedge) - 657kg, ASM, Semi-Act Laser
                { num = 4, CLSID = "{X-29L}" },  -- Kh-29L (AS-14 Kedge) - 657kg, ASM, Semi-Act Laser
                { num = 6, CLSID = "{9B25D316-0434-4954-868F-D51DB1A38DF0}" },  -- R-27R (AA-10 Alamo A) - Semi-Act Rdr
                { num = 7, CLSID = "{9B25D316-0434-4954-868F-D51DB1A38DF0}" },  -- R-27R (AA-10 Alamo A) - Semi-Act Rdr
                { num = 9, CLSID = "{X-29L}" },  -- Kh-29L (AS-14 Kedge) - 657kg, ASM, Semi-Act Laser
                { num = 10, CLSID = "{X-29L}" },  -- Kh-29L (AS-14 Kedge) - 657kg, ASM, Semi-Act Laser
                { num = 11, CLSID = "{FBC29BFE-3D24-4C64-B81D-941239D12249}" },  -- R-73 (AA-11 Archer) - Infra Red
                { num = 12, CLSID = "{ECM_POD_L_175V}" },  -- L175V Khibiny ECM pod
            },
        },
    },
    ["Tu-22M3"] = {
        strike = {
            source = "dcs", name = "FAB-500*33",
            fuel = 50000, chaff = 48, flare = 48, gun = 100,
            pylons = {
                { num = 3, CLSID = "{AD5E5863-08FC-4283-B92C-162E2B2BD3FF}" },  -- 33 x FAB-500M-62 - 500 kg GP Bomb LD
            },
        },
        airfield_strike = {
            source = "dcs", name = "FAB-250*33",
            fuel = 50000, chaff = 48, flare = 48, gun = 100,
            pylons = {
                { num = 3, CLSID = "{BDAD04AA-4D4A-4E51-B958-180A89F963CF}" },  -- 33 x OFAB-250-270 - 250 kg GP Bomb LD
            },
        },
    },
}
