"""Extract a mission's map's airfield radio frequencies into its data/airfield_frequencies.lua.

    python map_data_tools/airfield_frequencies.py <mission folder> [--dcs "C:\\Program Files\\Eagle Dynamics\\DCS World"] [--out ...]

Source: <DCS>\\Mods\\terrains\\<map>\\radio.lua (the map: MISSION.map in the mission's
mission_settings.lua), the map's own airfield radios (the tower /
ground / approach frequencies DCS's ATC uses, as on the airfield charts). Each entry's
radioId is "airfield<N>_0", N being the airbase's DCS id (Airbase:getID()), so the mission
looks a base up by its id. Per airfield: its ICAO-style label from the file's comment,
the VHF (118-136 MHz, the AN/ARC-222's band) and UHF tower frequencies in MHz.

The airfield traffic calls (roadmap.md item 7) go out on each field's VHF frequency.
Regex-driven: the file calls dofile and _(), which the table reader in dcslua.py doesn't
evaluate. Stdlib only.
"""

import argparse
import os
import re

from mission_folder import MISSION_FOLDER_HELP, MissionFolder

DEFAULT_DCS = r"C:\Program Files\Eagle Dynamics\DCS World"

LABEL = re.compile(r"^\s*--\s*(\S.*?)\s*$")
RADIO_ID = re.compile(r"radioId\s*=\s*'airfield(\d+)_0'")
BAND = re.compile(r"\[(VHF_HI|UHF)\]\s*=\s*\{\s*MODULATIONTYPE_\w+\s*,\s*([\d.]+)\s*\}")


def read(path):
    out, label = [], None
    entry = None
    for line in open(path, encoding="utf-8", errors="replace"):
        m = LABEL.match(line)
        if m:
            label = m.group(1)
            continue
        m = RADIO_ID.search(line)
        if m:
            entry = {"id": int(m.group(1)), "label": label or "?"}
            out.append(entry)
            continue
        if entry is not None and "frequency" in line:
            for band, hz in BAND.findall(line):
                entry["vhf" if band == "VHF_HI" else "uhf"] = float(hz) / 1e6
    return [e for e in out if "vhf" in e]


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("mission_folder", help=MISSION_FOLDER_HELP)
    parser.add_argument("--dcs", default=DEFAULT_DCS)
    parser.add_argument("--out", help="default: the mission's data/airfield_frequencies.lua")
    args = parser.parse_args()
    mission = MissionFolder(args.mission_folder)
    out = args.out or mission.data_file("airfield_frequencies.lua")
    source = os.path.join(args.dcs, "Mods", "terrains", mission.map_name, "radio.lua")
    entries = sorted(read(source), key=lambda e: e["id"])
    lines = [
        "-- The %s map's airfield radio frequencies, by DCS airbase id (Airbase:getID())." % mission.map_name,
        "-- GENERATED by map_data_tools/airfield_frequencies.py from",
        "-- Mods\\terrains\\%s\\radio.lua; don't edit by hand. MHz; vhf is the AN/ARC-222's band." % mission.map_name,
        "",
        "AIRFIELD_FREQUENCIES = {",
    ]
    for e in entries:
        lines.append("    [%d] = { label = %-30s vhf = %.3f, uhf = %.3f }," % (
            e["id"], '"%s",' % e["label"].replace('"', ""), e["vhf"], e.get("uhf", 0)))
    lines.append("}")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d airfields to %s" % (len(entries), out))


if __name__ == "__main__":
    main()
