-- The spawn sites of one 100 km tile of the Afghanistan map, from the whole-map survey 2026-10-08_1301; see
-- ..\spawn_sites_index.lua for the rules and every tile. Generated by map_data_tools/find_spawn_sites.py; do not hand-edit.
-- One site per line: number, x, z, latitude, longitude, height_m, rise_m (metres; x north, z east,
-- DCS's own; degrees as DCS converts them).

SPAWN_SITES_TILE = {
    tile = "tile_x+0200_z+0400", x_min = 200000, x_max = 300000, z_min = 400000, z_max = 500000,
    sites = {
        { 209573, 254200, 400900, 36.01665, 70.77267, 2582, 9 },
        { 214892, 270200, 466300, 36.11029, 71.50636, 4494, 3 },
        { 218503, 280500, 433400, 36.22753, 71.15420, 3455, 7 },
        { 218854, 281500, 433300, 36.23653, 71.15403, 3439, 13 },
        { 220173, 285300, 495200, 36.22168, 71.83895, 6138, 9 },
        { 225384, 298600, 494600, 36.34065, 71.84581, 4534, 15 },
        { 225481, 298800, 495800, 36.34144, 71.85923, 4509, 12 },
    },
}
