-- The Caucasus map's airfield radio frequencies, by DCS airbase id (Airbase:getID()).
-- GENERATED by map_data_tools/airfield_frequencies.py from
-- Mods\terrains\Caucasus\radio.lua; don't edit by hand. MHz; vhf is the AN/ARC-222's band.

AIRFIELD_FREQUENCIES = {
    [12] = { label = "Anapa",                       vhf = 121.000, uhf = 250.000 },
    [13] = { label = "Krasnodar",                   vhf = 122.000, uhf = 251.000 },
    [14] = { label = "Novorossiysk",                vhf = 123.000, uhf = 252.000 },
    [15] = { label = "Krymsk",                      vhf = 124.000, uhf = 253.000 },
    [16] = { label = "Maykop",                      vhf = 125.000, uhf = 254.000 },
    [17] = { label = "Gelendzhik",                  vhf = 126.000, uhf = 255.000 },
    [18] = { label = "Sochi",                       vhf = 127.000, uhf = 256.000 },
    [19] = { label = "Krasnodar_P",                 vhf = 128.000, uhf = 257.000 },
    [20] = { label = "Sukhumi",                     vhf = 129.000, uhf = 258.000 },
    [21] = { label = "Gudauta",                     vhf = 130.000, uhf = 259.000 },
    [22] = { label = "Batumi",                      vhf = 131.000, uhf = 260.000 },
    [23] = { label = "Senaki",                      vhf = 132.000, uhf = 261.000 },
    [24] = { label = "KOBULETI",                    vhf = 133.000, uhf = 262.000 },
    [25] = { label = "KUTAISI",                     vhf = 134.000, uhf = 263.000 },
    [26] = { label = "MinVody",                     vhf = 135.000, uhf = 264.000 },
    [27] = { label = "Nalchick",                    vhf = 136.000, uhf = 265.000 },
    [28] = { label = "Mozdok",                      vhf = 137.000, uhf = 266.000 },
    [29] = { label = "Lochini",                     vhf = 138.000, uhf = 267.000 },
    [30] = { label = "TbilisiMilitary",             vhf = 139.000, uhf = 268.000 },
    [31] = { label = "Vaziani",                     vhf = 140.000, uhf = 269.000 },
    [32] = { label = "Beslan",                      vhf = 141.000, uhf = 270.000 },
}
